name: 'Ember Asset Size'
description: 'Find out how much of a change to your asset size a PR will have'
author: 'Chris Manson'
branding:
  icon: 'bar-chart-2'
  color: 'orange'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  update-comments:
    description: 'Optional: Set to true to update existing asset size comment instead of creating a new one each time'
  working-directory:
    description: 'The directory to run the action from'
    required: false
    default: ''
  use-pr-artifacts:
    description: 'If production assets have been built in a previous step and downloaded for this step, analyze those instead of re-building'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
