name: 'Ember Asset Size'
description: 'Find out how much of a change to your asset size a PR will have'
author: 'Chris Manson'
branding:
  icon: 'bar-chart-2'
  color: 'orange'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  working-directory:
    description: 'The directory to run the action from'
runs:
  using: 'node12'
  main: 'index.js'
